### ISSUE TITLE
German translation ...

### ISSUE THREAD

**Issue by chsinpc** [zaps166/mate-xfce4-panel-plugin-loader-applet#3]
Hello zaps166,

you wrote a great applet, I'm using it with xfce whisker menu, places and weather applet.
For your further development, you can add the german translation file de.txt (attached below),
Just rename it to de.po.
[de.txt](https://github.com/zaps166/mate-xfce4-panel-plugin-loader-applet/files/33231/de.txt)

Greetings
chsinpc

**Comment by zaps166** [comment]
Hi, thanks chsinpc!
Could you try if it works: https://github.com/zaps166/mate-xfce4-panel-plugin-loader-applet/commit/43792f3d401eb5228ddf22484f635dbaf8e6b364 ?

**Comment by chsinpc** [comment]
Just works fine. I had to log out and log in after installing. Then the imported xfce4 applets have german language.

**Comment by zaps166** [comment]
Ok!
